{% set name = "azure-storage-queue" %}
{% set version = "12.1.1" %}
{% set sha256 = "08a59a7dcad2fb7980453773ef8ee32a27794f2714522ed83280fa1ad4808959" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - azure-common >=1.1.5
    - azure-storage-common >=1.3.0,<1.4.0

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.queue

about:
  home: https://github.com/Azure/azure-storage-python
  license: Apache-2.0
  license_family: Apache
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: Microsoft Azure Storage Queue Client Library for Python

extra:
  recipe-maintainers:
    - xhochy
