{% set name = "azure-storage-queue" %}
{% set version = "12.1.0" %}
{% set sha256 = "e905457f23428c55d1cff4d35ad04d4ceb4cc52c87cf14c1c8faa1018d560c56" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - azure-common >=1.1.5
    - azure-storage-common >=1.3.0,<1.4.0

test:
  imports:
    - azure
    - azure.storage
    - azure.storage.queue

about:
  home: https://github.com/Azure/azure-storage-python
  license: Apache-2.0
  license_family: Apache
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  summary: 'Microsoft Azure Storage Queue Client Library for Python'

extra:
  recipe-maintainers:
    - xhochy
